type Company = {
  id: number;
  companyName: string;
};

export const companyList: Company[] = [
  { id: 1, companyName: "카카오" },
  { id: 2, companyName: "왓챠" },
  { id: 3, companyName: "컬리" },
  { id: 4, companyName: "우아한형제들" },
  { id: 5, companyName: "뱅크샐러드" },
  { id: 6, companyName: "NHN" },
  { id: 7, companyName: "하이퍼커넥트" },
  { id: 8, companyName: "요기요" },
  { id: 9, companyName: "이스트소프트" },
  { id: 10, companyName: "플랫팜" },
  { id: 11, companyName: "스포카" },
  { id: 12, companyName: "네이버플레이스" },
  { id: 13, companyName: "라인" },
  { id: 14, companyName: "리디" },
  { id: 15, companyName: "네이버" },
  { id: 16, companyName: "데보션" },
  { id: 17, companyName: "구글코리아" },
  { id: 18, companyName: "AWS코리아" },
  { id: 19, companyName: "데이블" },
  { id: 20, companyName: "토스" },
  { id: 21, companyName: "스마일게이트" },
  { id: 22, companyName: "롯데온" },
  { id: 23, companyName: "카카오엔터프라이즈" },
  { id: 24, companyName: "메가존클라우드" },
  { id: 25, companyName: "SKC&C" },
  { id: 26, companyName: "여기어때" },
  { id: 27, companyName: "원티드" },
  { id: 28, companyName: "비브로스" },
  { id: 29, companyName: "포스타입" },
  { id: 30, companyName: "지마켓" },
  { id: 31, companyName: "SK플래닛" },
  { id: 32, companyName: "AB180" },
  { id: 33, companyName: "데브시스터즈" },
  { id: 34, companyName: "넷마블" },
  { id: 35, companyName: "마키나락스" },
  { id: 36, companyName: "드라마앤컴패니" },
  { id: 37, companyName: "티몬" },
  { id: 38, companyName: "루닛" },
  { id: 39, companyName: "인프런" },
  { id: 40, companyName: "게임빌컴투스플랫폼" },
  { id: 41, companyName: "카카오페이" },
  { id: 42, companyName: "덴티움" },
  { id: 43, companyName: "사람인" },
  { id: 44, companyName: "올리브영" },
  { id: 45, companyName: "티빙" },
  { id: 46, companyName: "11번가" },
  { id: 47, companyName: "다나와" },
  { id: 48, companyName: "농심" },
  { id: 49, companyName: "트렌비" },
  { id: 50, companyName: "교보DTS" },
  { id: 51, companyName: "중고나라" },
  { id: 52, companyName: "씨에스리" },
  { id: 53, companyName: "글루시스" },
  { id: 54, companyName: "DND" },
  { id: 55, companyName: "LG유플러스" },
];

export const companyMap: {
  [key: string]: number;
} = {
  카카오: 1,
  왓챠: 2,
  컬리: 3,
  우아한형제들: 4,
  뱅크샐러드: 5,
  NHN: 6,
  하이퍼커넥트: 7,
  요기요: 8,
  이스트소프트: 9,
  플랫팜: 10,
  스포카: 11,
  네이버플레이스: 12,
  라인: 13,
  리디: 14,
  네이버: 15,
  데보션: 16,
  구글코리아: 17,
  AWS코리아: 18,
  데이블: 19,
  토스: 20,
  스마일게이트: 21,
  롯데온: 22,
  카카오엔터프라이즈: 23,
  메가존클라우드: 24,
  "SKC&C": 25,
  여기어때: 26,
  원티드: 27,
  비브로스: 28,
  포스타입: 29,
  지마켓: 30,
  SK플래닛: 31,
  AB180: 32,
  데브시스터즈: 33,
  넷마블: 34,
  마키나락스: 35,
  드라마앤컴패니: 36,
  티몬: 37,
  루닛: 38,
  인프런: 39,
  게임빌컴투스플랫폼: 40,
  카카오페이: 41,
  덴티움: 42,
  사람인: 43,
  올리브영: 44,
  티빙: 45,
  "11번가": 46,
  다나와: 47,
  농심: 48,
  트렌비: 49,
  교보DTS: 50,
  중고나라: 51,
  씨에스리: 52,
  글루시스: 53,
  DND: 54,
  LG유플러스: 55,
};
